name: bitmark_infinity
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - certifi=2025.10.5=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.8.90=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.8=3
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py312h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.13.1.3=0
  - libcurand=10.3.9.90=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py312h06a4308_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.18=hd6dcaed_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py312hcea889d_0
  - pip=25.0=py312h06a4308_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.9.0=py312h5eee18b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.9=h5148396_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - pytorch=2.5.1=py3.12_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pywavelets=1.9.0=py312hb25bd0a_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - setuptools=75.8.0=py312h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=3.1.0=py312
  - torchvision=0.20.1=py312_cu121
  - tornado=6.4.2=py312h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=py312h06a4308_0
  - urllib3=2.3.0=py312h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.0
      - accelerate==1.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - albucore==0.0.23
      - albumentations==1.4.24
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - appdirs==1.4.4
      - arxiv-latex-cleaner==1.0.8
      - attrs==25.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - braceexpand==0.1.7
      - click==8.1.8
      - color-matcher==0.6.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - controlnet-aux==0.0.10
      - cycler==0.12.1
      - dataclasses==0.6
      - datasets==3.5.0
      - ddt==1.7.2
      - decord==0.6.0
      - defusedxml==0.7.1
      - diffusers==0.33.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - docstring-parser==0.16
      - docutils==0.21.2
      - easydict==1.13
      - einops==0.8.1
      - exifread-nocycle==3.0.1
      - fairscale==0.4.13
      - fastapi==0.115.12
      - fastjsonschema==2.21.2
      - ffmpy==0.5.0
      - fire==0.5.0
      - flash-attn==2.7.4.post1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glob2==0.7
      - gputil==1.4.0
      - gradio==5.22.0
      - gradio-client==1.8.0
      - groovy==0.1.2
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - humanfriendly==10.0
      - image-reward==1.5
      - imageio==2.37.0
      - img2dataset==1.45.0
      - ipython==8.12.3
      - joblib==1.4.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mistune==3.1.4
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nltk==3.9.1
      - normalizer==0.2.1
      - numpy==1.26.4
      - nvidia-ml-py==12.570.86
      - omegaconf==2.3.0
      - onnxruntime==1.22.1
      - open-clip-torch==2.31.0
      - openai==0.28.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - orjson==3.10.15
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - pathlib==1.0.1
      - pipreqs==0.5.0
      - platformdirs==4.3.7
      - propcache==0.3.0
      - protobuf==4.25.8
      - pyarrow==15.0.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pyparsing==3.2.1
      - python-multipart==0.0.20
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.5.2
      - pytz==2025.1
      - referencing==0.36.2
      - regex==2024.11.6
      - rfc3986==1.5.0
      - rich==13.9.4
      - rpds-py==0.27.1
      - ruff==0.11.2
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - simsimd==6.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - starlette==0.46.1
      - stringzilla==3.12.5
      - sympy==1.13.1
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - timm==0.6.13
      - tinycss2==1.4.0
      - tokenizers==0.15.2
      - tomlkit==0.13.2
      - torch-fidelity==0.3.0
      - torchmetrics==1.7.1
      - tqdm==4.67.1
      - transformers==4.37.2
      - trustmark==0.8.0
      - typed-argument-parser==1.10.1
      - typer==0.15.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.1
      - uvicorn==0.34.0
      - wandb==0.16.6
      - webdataset==0.2.111
      - webencodings==0.5.1
      - websockets==15.0.1
      - xxhash==3.5.0
      - yarg==0.1.9
      - yarl==1.18.3
